features:
  -
    id: sdg
    logo: /images/sdg.svg
    title: SDG classification
    tag: Demo
    description: |
      SDG classification allows institutions to gain rapid insights into the current mapping of their research outputs to the 17 UN SDG goals, significantly reducing the manual effort required to map research outputs to global sustainability objectives.
    action:
      caption: Try it now
      url: /labs/sdg
  -
    id: rrs
    logo: /images/rrs.svg
    title: RRS identification
    tag: Demo
    description: |
      RRS checker provides an easy way to find Rights Retention Strategy statements in papers. 
    action:
      caption: Try it now
      url: /rights-retention
  -
    id: das
    logo: /images/das.svg
    title: Data Availability Statement identification
    tag: Demo
    description: |
      DAS checker helps researchers, publishers, and repository managers to automatically identify whether a research paper includes a Data Availability Statement. This tool ensures transparency, improves metadata quality, and supports compliance with Open Science policies.
    action:
      caption: Try it now
      url: /data-availability
