features:
  -
    id: sdg
    logo: /images/sdg.svg
    title: SDG classification
    tag: Demo
    description: |
      SDG classification allows institutions to gain rapid insights into the current mapping of their research outputs to the 17 UN SDG goals, significantly reducing the manual effort required to map research outputs to global sustainability objectives.
    action:
      caption: Try it now
      url: /labs/sdg
  -
    id: rrs
    logo: /images/rrs.svg
    title: RRS identification
    tag: Demo
    description: |
      RRS checker provides an easy way to find Rights Retention Strategy statements in papers. 
    action:
      caption: Try it now
      url: /rights-retention
  -
    id: das
    logo: /images/das.svg
    title: Data Availability Statement identification
    tag: Demo
    description: |
      DAS checker helps researchers, publishers, and repository managers to automatically identify whether a research paper includes a Data Availability Statement. This tool ensures transparency, improves metadata quality, and supports compliance with Open Science policies.
    action:
      caption: Try it now
      url: /data-availability
  - id: diagnostics
    logo: /images/diagnostics.svg
    title: Repository Indexability Diagnostics
    tag: Diagnostic
    description: |
      This tool will run basic diagnostic tests against your repository to find out if it is not blocking indexing systems. You just need to enter your repository URL, OAI-PMH base URL, or domain name in the form and you will get a report of all diagnostic tests with details and recommendations.
    action:
      caption: Try it now
      url: /blocking-diagnostic
