backend:
  name: github
  repo: oacore/content
media_folder: uploads
public_folder: ''
collections:
  -
    label: Pages
    name: pages
    files:
      -
        file: about.yml
        name: about
        label: About
        fields:
          - 
            name: title
            label: Title
            widget: string
          -
            name: description
            label: Description
            widget: text
          -
            name: mission
            label: Mission
            widget: object
            fields:
              -
                name: title
                label: Heading
                widget: string
                default: Mission
              -
                name: body
                label: Content
                widget: markdown
