site_url: https://oacore.github.io/content

backend:
  name: github
  repo: oacore/content
  branch: netlifycms
  site_domain: content.oacore.vercel.app
  cms_label_prefix: edit/

  base_url: https://content.oacore.vercel.app
  auth_endpoint: api/auth/begin

media_folder: uploads
public_folder: ''

publish_mode: editorial_workflow

collections:
  -
    label: CORE
    name: core
    files:
      -
        file: about.yml
        name: about
        label: About
        fields:
          -
            name: title
            label: Title
            widget: string
          -
            name: description
            label: Description
            widget: text
          -
            name: mission
            label: Mission
            widget: object
            fields:
              -
                name: title
                label: Heading
                widget: string
                default: Mission
              -
                name: body
                label: Content
                widget: markdown
