id: rrs
title: Rights Retention Strategy statement identification demo
tagline:  RRS checker provides an easy way to find Rights Retention Strategy statements in papers. You can test it by uploading a paper (PDF) below.
