features:
  - title: Advisory Board
    url: /governance/advisory
  - title: Board of Supporters
    url: /governance/supporters
  - title: Research network
    url: /governance/research
  - title: The Open University Stakeholders group
    url: https://www.open.ac.uk
