title: CORE Consultancy
description: CORE aggregates (harvests) research papers from data providers from
  all over the world including institutional and subject repositories, open
  access and hybrid journal publishers.
headline: About CORE
tagline: Develop new applications with the CORE API.
