title: Advisory
tagline: Advisory Board
description: Our advisory board comprises of distinguished open research experts
  who advise on strategic directions and ensure mission alignment with the
  community needs.
