id: sdf
title: Classification of research papers according to the United Nations Sustainable Development Goals
tagline:  The Sustainable Development Goals or Global Goals are a collection of 17 interlinked global goals, designed to be a “blueprint to achieve a better and more sustainable future for all”. The SDGs were set up in 2015 by the United Nations General Assembly, and are intended to be achieved by 2030.
