id: membership
title: CORE Membership for data providers
tagline:  CORE is a mission-driven and not-for-profit endeavour and we rely on the generous support of our members to support and sustain the service.
