title: CORE Consultancy
description: CORE aggregates (indexes) research papers from data providers from
  all over the world including institutional and subject repositories, open
  access and hybrid journal publishers.
tagline: CORE aggregates (indexes) research papers from data providers from all
  over the world including institutional and subject repositories, open access
  and hybrid journal publishers.
